### PR TITLE
Support GHC 8.8.1 (fixes #19)

### LINKED ISSUE #19: GHC 8.8 support
If I try to build the package with 8.8, I get

```
Building library for ghc-dump-core-0.1.1.0..

on the commandline: warning:
    -Wnoncanonical-monadfail-instances is deprecated: fail is no longer a method of Monad
[1 of 3] Compiling GhcDump.Ast      ( GhcDump/Ast.hs, dist/build/GhcDump/Ast.o )
[2 of 3] Compiling GhcDump.Convert  ( GhcDump/Convert.hs, dist/build/GhcDump/Convert.o )

GhcDump/Convert.hs:196:7: error:
    Not in scope: data constructor ‘Literal.MachChar’
    Perhaps you meant one of these:
      ‘Literal.LitChar’ (imported from Literal),
      ‘Literal.LitChar’ (imported from Literal)
    Module ‘Literal’ does not export ‘MachChar’.
    |
196 |       Literal.MachChar x -> Ast.MachChar x
    |       ^^^^^^^^^^^^^^^^

GhcDump/Convert.hs:197:7: error:
    Not in scope: data constructor ‘Literal.MachStr’
    Module ‘Literal’ does not export ‘MachStr’.
    |
197 |       Literal.MachStr x -> Ast.MachStr x
    |       ^^^^^^^^^^^^^^^

GhcDump/Convert.hs:198:7: error:
    Not in scope: data constructor ‘Literal.MachNullAddr’
    Perhaps you meant one of these:
      ‘Literal.LitNullAddr’ (imported from Literal),
      ‘Literal.LitNullAddr’ (imported from Literal)
    Module ‘Literal’ does not export ‘MachNullAddr’.
    |
198 |       Literal.MachNullAddr -> Ast.MachNullAddr
    |       ^^^^^^^^^^^^^^^^^^^^

GhcDump/Convert.hs:215:7: error:
    Not in scope: data constructor ‘Literal.MachFloat’
    Perhaps you meant one of these:
      ‘Literal.LitFloat’ (imported from Literal),
      ‘Literal.LitFloat’ (imported from Literal)
    Module ‘Literal’ does not export ‘MachFloat’.
    |
215 |       Literal.MachFloat x -> Ast.MachFloat x
    |       ^^^^^^^^^^^^^^^^^

GhcDump/Convert.hs:216:7: error:
    Not in scope: data constructor ‘Literal.MachDouble’
    Perhaps you meant one of these:
      ‘Literal.LitDouble’ (imported from Literal),
      ‘Literal.LitDouble’ (imported from Literal),
      variable ‘Literal.mkLitDouble’ (imported from Literal)
    Module ‘Literal’ does not export ‘MachDouble’.
    |
216 |       Literal.MachDouble x -> Ast.MachDouble x
    |       ^^^^^^^^^^^^^^^^^^

GhcDump/Convert.hs:217:7: error:
    Not in scope: data constructor ‘Literal.MachLabel’
    Perhaps you meant one of these:
      ‘Literal.LitLabel’ (imported from Literal),
      ‘Literal.LitLabel’ (imported from Literal)
    Module ‘Literal’ does not export ‘MachLabel’.
    |
217 |       Literal.MachLabel x _ _ -> Ast.MachLabel $ fastStringToText  x
    |       ^^^^^^^^^^^^^^^^^

GhcDump/Convert.hs:238:25: error:
    Not in scope: data constructor ‘Var.TvBndr’
    Perhaps you meant ‘Var.Bndr’ (imported from Var)
    Module ‘Var’ does not export ‘TvBndr’.
    |
238 | cvtType (Type.ForAllTy (Var.TvBndr b _) t) = Ast.ForAllTy (cvtBinder b) (cvtType t)

```

### PR DESCRIPTION
**Pull request by maoe**
This PR adds support for GHC 8.8.1. The dependency on regex-tdfa-text has been superseded by the latest regex-tdfa.

### CODE REVIEW

**Comment by hvr** [comment]
@maoe can you try this PR with the branch tip of https://github.com/haskell-hvr/regex-tdfa/commits/master ?

**Comment by maoe** [comment]
> @maoe can you try this PR with the branch tip of https://github.com/haskell-hvr/regex-tdfa/commits/master ?

Sure. I confirmed locally that --filter option worked fine. I just pushed 31c096c to make sure CI passes with all GHC versions.

**Comment by maoe** [comment]
CI was fine with the latest regex-tdfa. I've removed the source-repository-package change. Now this is ready for review.

**Comment by hvr** [comment]
@maoe Btw, what are regexes being used in ghc-dump for? Are they performance critical? I'm asking because I'm searching for real-world benchmarks to measure how much -O2 vs -O1 matters for `regex-tdfa`

**Comment by hvr** [comment]
@maoe fyi, http://hackage.haskell.org/package/regex-tdfa-1.3.1.0

**Comment by maoe** [comment]
> @maoe Btw, what are regexes being used in ghc-dump for? Are they performance critical? I'm asking because I'm searching for real-world benchmarks to measure how much -O2 vs -O1 matters for `regex-tdfa`

ghc-dump-util uses regexes to filter output by a binding name. I'd say the performance is not critical unless the Core file is exceptionally big.

> @maoe fyi, http://hackage.haskell.org/package/regex-tdfa-1.3.1.0

Thanks! I've confirmed this PR builds fine with the release version.

**Pull request merged**
